[package]
name = "sbis_build_status"
version = "0.0.2"
authors = ["as.larin@tensor.ru"]
edition = "2018"

[dependencies]
telegram-bot = "0.7"
futures = "0.3"
tokio = {version = "0.2", features = ["macros", "time"]}
sysinfo = "0.14"
chrono = "0.4"