[package]
name = "sbis_build_status"
version = "0.0.2"
authors = ["as.larin@tensor.ru"]
edition = "2018"

[dependencies]
telegram-bot = "0.6.3"
futures = "0.1"
tokio-core = "0.1"
tokio = "0.1"
sysinfo = "0.12"
chrono = "0.4"