[package]
name = "sbis_build_status"
version = "0.0.3"
authors = ["as.larin@tensor.ru"]
edition = "2018"

[dependencies]
chrono = "0.4"
futures = "0.3"
rust-ini = "0.17"
sysinfo = "0.17"
telegram-bot = "0.8"
tokio = {version = "0.2", features = ["macros", "time"]}